# Generated by Django 4.2.11 on 2024-04-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parttimeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.CharField(default='811255dd', max_length=20, unique=True),
        ),
    ]
